[versions]
agp = "8.0.1"
compileSdk = "33"
targetSdk = "33"
minSdk = "21"
#Kotlin
kotlin = "1.8.21"
kotlinx-serialization = "1.5.1"
kotlinx-coroutines = "1.7.1"
#Compose
composecompiler = "1.4.7"
#Squareup
squareup-okhttp3 = "4.11.0"
squareup-retrofit2 = "2.9.0"
#Android
androidx-activity = "1.7.2"
androidx-appcompat = "1.6.1"
#Google
google-hilt = "2.46.1"
google-maps = "17.0.0"
#Apollo
apollo3 = "3.8.1"
#Others
lifecycle = "2.6.1"
accompanist = "0.31.2-alpha"
braze = "24.3.0"
coil = "2.4.0"
compose-destinations = "1.9.42-beta"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-play-publisher = { id = "com.github.triplet.play", version = "3.8.1" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
google-gms = { id = "com.google.gms.google-services", version = "4.3.15" }
ksp = { id = "com.google.devtools.ksp", version = "1.8.21-1.0.11" }
apollo3 = { id = "com.apollographql.apollo3", version.ref = "apollo3" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.5" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version = "4.0.0" }

[libraries]
#Classpath
classpath-javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }

#Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
#Squareup
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp3" }
squareup-okhttp3-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup-okhttp3" }
squareup-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareup-retrofit2" }
squareup-retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }
#Androidx
androidx-core = { module = "androidx.core:core-ktx", version = "1.11.0-beta01" }
androidx-activity-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version = "1.6.0-rc01" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
#androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-preference = { module = "androidx.preference:preference-ktx", version = "1.2.0" }
androidx-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
androidx-navigation = { module = "androidx.navigation:navigation-compose", version = "2.6.0-rc02" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2023.05.01" }
androidx-compose-bom-chrisbanes = { module = "dev.chrisbanes.compose:compose-bom", version = "2023.04.00-beta01" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.1-rc01" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version = "1.1.0-beta02" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }
#Google
# We need to use alpha because of crash on hiding keyboard in MaterialDatePicker
google-material = { module = "com.google.android.material:material", version = "1.9.0" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "google-hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-hilt" }
google-auth = { module = "com.google.android.gms:play-services-auth", version = "20.5.0" }
google-play-core = { module = "com.google.android.play:core-ktx", version = "1.8.1" }
google-places = { module = "com.google.android.libraries.places:places", version = "3.1.0" }
#Apollo
apollo3-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo3" }
apollo3-adapters = { module = "com.apollographql.apollo3:apollo-adapters", version.ref = "apollo3" }
apollo3-http-cache = { module = "com.apollographql.apollo3:apollo-http-cache", version.ref = "apollo3" }
apollo3-normalized-cache = { module = "com.apollographql.apollo3:apollo-normalized-cache", version.ref = "apollo3" }
apollo3-normalized-cache-sqlite = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite", version.ref = "apollo3" }

lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
accompanist-system-ui-controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-nav-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version = "32.0.0" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

braze-ui = { module = "com.braze:android-sdk-ui", version.ref = "braze" }
braze-location = { module = "com.braze:android-sdk-location", version.ref = "braze" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
facebook-login = { module = "com.facebook.android:facebook-login", version = "16.0.1" }
lokalise = { module = "com.lokalise.android:sdk", version = "2.2.0-lite" }
stripe = { module = "com.stripe:stripe-android", version = "20.25.3" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
coreDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }

easyImage = { module = "com.github.jkwiecien:EasyImage", version = "2.1.1" }
photoView = { module = "com.github.chrisbanes:PhotoView", version = "2.3.0" }
circleindicator = { module = "me.relex:circleindicator", version = "2.1.6" }
progressbutton = { module = "com.github.razir.progressbutton:progressbutton", version = "2.1.0" }
libphonenumber-android = { module = "io.michaelrocks:libphonenumber-android", version = "8.13.11" }
ucrop = { module = "com.github.yalantis:ucrop", version = "2.2.8" }
viewbindingpropertydelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version = "1.5.9" }

[bundles]
androidx-compose = [
    "androidx-compose-ui", "androidx-compose-ui-util", "androidx-compose-ui-tooling",
    "androidx-compose-foundation", "androidx-compose-foundation-layout",
    "androidx-compose-runtime", "androidx-compose-animation",
    "androidx-compose-material", "androidx-compose-material-icons-extended"
]
firebase = ["firebase-crashlytics", "firebase-analytics", "firebase-config", "firebase-messaging"]
lifecycle = ["lifecycle-runtime-compose", "lifecycle-livedata-ktx", "lifecycle-viewmodel-savedstate", "lifecycle-viewmodel-ktx", "lifecycle-viewmodel-compose"]
accompanist = ["accompanist-system-ui-controller", "accompanist-nav-material"]
braze = ["braze-ui", "braze-location"]
coil = ["coil-compose", "coil-video"]