[versions]
agp = "8.1.0-rc01"
compileSdk = "33"
targetSdk = "33"
minSdk = "21"
#Kotlin
kotlin = "1.8.21"
kotlinx-coroutines = "1.7.1"
#Compose
composecompiler = "1.4.7"
#Android
androidx-activity = "1.7.2"
#Others
lifecycle = "2.6.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
#Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

#Androidx
androidx-core = { module = "androidx.core:core-ktx", version = "1.11.0-beta01" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2023.05.01" } # compose = 1.4.3
androidx-compose-bom-chrisbanes = { module = "dev.chrisbanes.compose:compose-bom", version = "2023.04.00-beta01" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material = { module = "androidx.compose.material:material" }

lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
coreDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }

[bundles]